separators = [ '{', '}', '(', ')', ';', ':', ]
operators = ['Diferit' , 'Mare', 'Mic', 'MareEgal', 'MicEgal' , 'Egal' , 'Plus', 'Minus', 'PlusPlus' , 'MinusMinus' , 'Ori', 'Pe' ,'Si', 'Sau' , 'Diferit']
identifier = ['Intreg', 'Sfoara' , 'Sir']
reservedWords = ['CatTimp' , 'Pentru' , 'Daca' , 'Altfel' , 'Scrie' , 'Citeste' , 'Ia' , 'Program', '\n']
dereferences = ['[',']']
operations = ['Diferit' , 'Mare', 'Mic', 'MareEgal', 'MicEgal' , 'Egal' , 'Plus', 'Minus', 'PlusPlus' , 'MinusMinus' , 'Ori', 'Pe' ,'Si', 'Sau','Scrie','Ia']
